#ifndef SOAP_TYPE_xsd__duration
#define SOAP_TYPE_xsd__duration (154)
typedef long long xsd__duration;
#endif

/* soapStub.h
   Generated by gSOAP 2.8.95 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#define SOAP_WSDD_2005
#define SOAP_WSA_200408
#define SOAP_NAMESPACE_OF_wsa	"http://schemas.xmlsoap.org/ws/2004/08/addressing"
#define SOAP_NAMESPACE_OF_wsdd	"http://schemas.xmlsoap.org/ws/2005/04/discovery"
#define SOAP_NAMESPACE_OF_tdn	"http://www.onvif.org/ver10/network/wsdl"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20895
# error "GSOAP VERSION 20895 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumeration Types                                                          *
 *                                                                            *
\******************************************************************************/


/* wsa.h:123 */
#ifndef SOAP_TYPE_wsa__RelationshipTypeValues
#define SOAP_TYPE_wsa__RelationshipTypeValues (12)
/* wsa:RelationshipTypeValues */
typedef enum wsa__RelationshipTypeValues {
	wsa__Reply = 0
} wsa__RelationshipTypeValues;
#endif

/* wsa.h:131 */
#ifndef SOAP_TYPE_wsa__FaultSubcodeValues
#define SOAP_TYPE_wsa__FaultSubcodeValues (13)
/* wsa:FaultSubcodeValues */
typedef enum wsa__FaultSubcodeValues {
	wsa__InvalidMessageInformationHeader = 0,
	wsa__MessageInformationHeaderRequired = 1,
	wsa__DestinationUnreachable = 2,
	wsa__ActionNotSupported = 3,
	wsa__EndpointUnavailable = 4
} wsa__FaultSubcodeValues;
#endif

/* wsdd10.h:100 */
#ifndef SOAP_TYPE_wsdd__FaultCodeType
#define SOAP_TYPE_wsdd__FaultCodeType (58)
/* wsdd:FaultCodeType */
typedef enum wsdd__FaultCodeType {
	wsdd__MatchingRuleNotSupported = 0
} wsdd__FaultCodeType;
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Structs and Unions                                                         *
 *                                                                            *
\******************************************************************************/

typedef struct wsa__EndpointReferenceType wsa__EndpointReferenceType;	/* wsa.h:98 */
typedef struct wsa__ReferencePropertiesType wsa__ReferencePropertiesType;	/* wsa.h:101 */
typedef struct wsa__ReferenceParametersType wsa__ReferenceParametersType;	/* wsa.h:104 */
typedef struct wsa__ServiceNameType wsa__ServiceNameType;	/* wsa.h:107 */
typedef struct wsa__Relationship wsa__Relationship;	/* wsa.h:110 */
typedef struct wsdd__HelloType wsdd__HelloType;	/* wsdd10.h:55 */
typedef struct wsdd__ByeType wsdd__ByeType;	/* wsdd10.h:57 */
typedef struct wsdd__ProbeType wsdd__ProbeType;	/* wsdd10.h:59 */
typedef struct wsdd__ProbeMatchesType wsdd__ProbeMatchesType;	/* wsdd10.h:61 */
typedef struct wsdd__ProbeMatchType wsdd__ProbeMatchType;	/* wsdd10.h:63 */
typedef struct wsdd__ResolveType wsdd__ResolveType;	/* wsdd10.h:65 */
typedef struct wsdd__ResolveMatchesType wsdd__ResolveMatchesType;	/* wsdd10.h:67 */
typedef struct wsdd__ResolveMatchType wsdd__ResolveMatchType;	/* wsdd10.h:69 */
typedef struct wsdd__SecurityType wsdd__SecurityType;	/* wsdd10.h:73 */
typedef struct wsdd__SigType wsdd__SigType;	/* wsdd10.h:75 */
typedef struct wsdd__ScopesType wsdd__ScopesType;	/* wsdd10.h:71 */
typedef struct wsdd__AppSequenceType wsdd__AppSequenceType;	/* wsdd10.h:77 */
struct __wsdd__Hello;	/* wsdx.h:67 */
struct __wsdd__Bye;	/* wsdx.h:76 */
struct __wsdd__Probe;	/* wsdx.h:85 */
struct __wsdd__ProbeMatches;	/* wsdx.h:94 */
struct __wsdd__Resolve;	/* wsdx.h:103 */
struct __wsdd__ResolveMatches;	/* wsdx.h:112 */
struct __tdn__Hello;	/* onvif.h:298 */
struct __tdn__Bye;	/* onvif.h:353 */
struct __tdn__Probe;	/* onvif.h:408 */

/* wsa.h:98 */
#ifndef SOAP_TYPE_wsa__EndpointReferenceType
#define SOAP_TYPE_wsa__EndpointReferenceType (7)
/* complex XML schema type 'wsa:EndpointReferenceType': */
struct wsa__EndpointReferenceType {
        /** Required element 'wsa:Address' of XML schema type 'xsd:string' */
        char *Address;
        /** Optional element 'wsa:ReferenceProperties' of XML schema type 'wsa:ReferencePropertiesType' */
        struct wsa__ReferencePropertiesType *ReferenceProperties;
        /** Optional element 'wsa:ReferenceParameters' of XML schema type 'wsa:ReferenceParametersType' */
        struct wsa__ReferenceParametersType *ReferenceParameters;
        /** Optional element 'wsa:PortType' of XML schema type 'xsd:QName' */
        char **PortType;
        /** Optional element 'wsa:ServiceName' of XML schema type 'wsa:ServiceNameType' */
        struct wsa__ServiceNameType *ServiceName;
        /** Sequence of elements '-any' of XML schema type 'xsd:anyType' stored in dynamic array __any of length __size */
        int __size;
        char **__any;
        /** Optional attribute '-anyAttribute' of XML schema type 'xsd:anyType' */
        char *__anyAttribute;
};
#endif

/* wsa.h:101 */
#ifndef SOAP_TYPE_wsa__ReferencePropertiesType
#define SOAP_TYPE_wsa__ReferencePropertiesType (8)
/* complex XML schema type 'wsa:ReferencePropertiesType': */
struct wsa__ReferencePropertiesType {
        /** Sequence of elements '-any' of XML schema type 'xsd:anyType' stored in dynamic array __any of length __size */
        int __size;
        char **__any;
};
#endif

/* wsa.h:104 */
#ifndef SOAP_TYPE_wsa__ReferenceParametersType
#define SOAP_TYPE_wsa__ReferenceParametersType (9)
/* complex XML schema type 'wsa:ReferenceParametersType': */
struct wsa__ReferenceParametersType {
        /** Sequence of elements '-any' of XML schema type 'xsd:anyType' stored in dynamic array __any of length __size */
        int __size;
        char **__any;
};
#endif

/* wsa.h:107 */
#ifndef SOAP_TYPE_wsa__ServiceNameType
#define SOAP_TYPE_wsa__ServiceNameType (10)
/* simple XML schema type 'wsa:ServiceNameType': */
struct wsa__ServiceNameType {
        /** Simple content of XML schema type 'xsd:QName' wrapped by this struct */
        char *__item;
        /** Optional attribute 'PortName' of XML schema type 'xsd:string' */
        char *PortName;
        /** Optional attribute '-anyAttribute' of XML schema type 'xsd:anyType' */
        char *__anyAttribute;
};
#endif

/* wsa.h:110 */
#ifndef SOAP_TYPE_wsa__Relationship
#define SOAP_TYPE_wsa__Relationship (11)
/* simple XML schema type 'wsa:Relationship': */
struct wsa__Relationship {
        /** Simple content of XML schema type 'xsd:string' wrapped by this struct */
        char *__item;
        /** Optional attribute 'RelationshipType' of XML schema type 'xsd:QName' */
        char *RelationshipType;
        /** Optional attribute '-anyAttribute' of XML schema type 'xsd:anyType' */
        char *__anyAttribute;
};
#endif

/* wsa.h:254 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (29)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
        /** Optional element 'wsa:MessageID' of XML schema type 'wsa:MessageID' */
        char *wsa__MessageID;
        /** Optional element 'wsa:RelatesTo' of XML schema type 'wsa:RelatesTo' */
        struct wsa__Relationship *wsa__RelatesTo;
        /** Optional element 'wsa:From' of XML schema type 'wsa:From' */
        struct wsa__EndpointReferenceType *wsa__From;
        /** MustUnderstand */
        struct wsa__EndpointReferenceType *wsa__ReplyTo;
        /** MustUnderstand */
        struct wsa__EndpointReferenceType *wsa__FaultTo;
        /** MustUnderstand */
        char *wsa__To;
        /** MustUnderstand */
        char *wsa__Action;
        /** Optional element 'wsdd:AppSequence' of XML schema type 'wsdd:AppSequenceType' */
        struct wsdd__AppSequenceType *wsdd__AppSequence;
};
#endif
#endif

/* wsa.h:270 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (34)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_<typename> assigned to __type */
        /** Do not create a cyclic data structure through this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
};
#endif
#endif

/* wsa.h:271 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (36)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
        /** Optional element 'SOAP-ENV:Value' of XML schema type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
};
#endif
#endif

/* wsa.h:272 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (38)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
        /** Optional element 'SOAP-ENV:Text' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Text;
};
#endif
#endif

/* wsa.h:277 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (42)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
        /** Optional element 'faultcode' of XML schema type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XML schema type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XML schema type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XML schema type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};
#endif
#endif

/* wsdd10.h:55 */
#ifndef SOAP_TYPE_wsdd__HelloType
#define SOAP_TYPE_wsdd__HelloType (43)
/* complex XML schema type 'wsdd:HelloType': */
struct wsdd__HelloType {
        /** Required element 'wsa:EndpointReference' of XML schema type 'wsa:EndpointReference' */
        struct wsa__EndpointReferenceType wsa__EndpointReference;
        /** Optional element 'wsdd:Types' of XML schema type 'xsd:QName' */
        char *Types;
        /** Optional element 'wsdd:Scopes' of XML schema type 'wsdd:ScopesType' */
        struct wsdd__ScopesType *Scopes;
        /** Optional element 'wsdd:XAddrs' of XML schema type 'wsdd:UriListType' */
        char *XAddrs;
        /** Required element 'wsdd:MetadataVersion' of XML schema type 'xsd:unsignedInt' */
        unsigned int MetadataVersion;
};
#endif

/* wsdd10.h:57 */
#ifndef SOAP_TYPE_wsdd__ByeType
#define SOAP_TYPE_wsdd__ByeType (44)
/* complex XML schema type 'wsdd:ByeType': */
struct wsdd__ByeType {
        /** Required element 'wsa:EndpointReference' of XML schema type 'wsa:EndpointReference' */
        struct wsa__EndpointReferenceType wsa__EndpointReference;
        /** Optional element 'wsdd:Types' of XML schema type 'xsd:QName' */
        char *Types;
        /** Optional element 'wsdd:Scopes' of XML schema type 'wsdd:ScopesType' */
        struct wsdd__ScopesType *Scopes;
        /** Optional element 'wsdd:XAddrs' of XML schema type 'wsdd:UriListType' */
        char *XAddrs;
        /** Optional element 'wsdd:MetadataVersion' of XML schema type 'xsd:unsignedInt' */
        unsigned int *MetadataVersion;
};
#endif

/* wsdd10.h:59 */
#ifndef SOAP_TYPE_wsdd__ProbeType
#define SOAP_TYPE_wsdd__ProbeType (45)
/* complex XML schema type 'wsdd:ProbeType': */
struct wsdd__ProbeType {
        /** Optional element 'wsdd:Types' of XML schema type 'xsd:QName' */
        char *Types;
        /** Optional element 'wsdd:Scopes' of XML schema type 'wsdd:ScopesType' */
        struct wsdd__ScopesType *Scopes;
};
#endif

/* wsdd10.h:61 */
#ifndef SOAP_TYPE_wsdd__ProbeMatchesType
#define SOAP_TYPE_wsdd__ProbeMatchesType (46)
/* complex XML schema type 'wsdd:ProbeMatchesType': */
struct wsdd__ProbeMatchesType {
        /** Sequence of elements 'wsdd:ProbeMatch' of XML schema type 'wsdd:ProbeMatchType' stored in dynamic array ProbeMatch of length __sizeProbeMatch */
        int __sizeProbeMatch;
        struct wsdd__ProbeMatchType *ProbeMatch;
};
#endif

/* wsdd10.h:63 */
#ifndef SOAP_TYPE_wsdd__ProbeMatchType
#define SOAP_TYPE_wsdd__ProbeMatchType (47)
/* complex XML schema type 'wsdd:ProbeMatchType': */
struct wsdd__ProbeMatchType {
        /** Required element 'wsa:EndpointReference' of XML schema type 'wsa:EndpointReference' */
        struct wsa__EndpointReferenceType wsa__EndpointReference;
        /** Optional element 'wsdd:Types' of XML schema type 'xsd:QName' */
        char *Types;
        /** Optional element 'wsdd:Scopes' of XML schema type 'wsdd:ScopesType' */
        struct wsdd__ScopesType *Scopes;
        /** Optional element 'wsdd:XAddrs' of XML schema type 'wsdd:UriListType' */
        char *XAddrs;
        /** Required element 'wsdd:MetadataVersion' of XML schema type 'xsd:unsignedInt' */
        unsigned int MetadataVersion;
};
#endif

/* wsdd10.h:65 */
#ifndef SOAP_TYPE_wsdd__ResolveType
#define SOAP_TYPE_wsdd__ResolveType (48)
/* complex XML schema type 'wsdd:ResolveType': */
struct wsdd__ResolveType {
        /** Required element 'wsa:EndpointReference' of XML schema type 'wsa:EndpointReference' */
        struct wsa__EndpointReferenceType wsa__EndpointReference;
};
#endif

/* wsdd10.h:67 */
#ifndef SOAP_TYPE_wsdd__ResolveMatchesType
#define SOAP_TYPE_wsdd__ResolveMatchesType (49)
/* complex XML schema type 'wsdd:ResolveMatchesType': */
struct wsdd__ResolveMatchesType {
        /** Optional element 'wsdd:ResolveMatch' of XML schema type 'wsdd:ResolveMatchType' */
        struct wsdd__ResolveMatchType *ResolveMatch;
};
#endif

/* wsdd10.h:69 */
#ifndef SOAP_TYPE_wsdd__ResolveMatchType
#define SOAP_TYPE_wsdd__ResolveMatchType (50)
/* complex XML schema type 'wsdd:ResolveMatchType': */
struct wsdd__ResolveMatchType {
        /** Required element 'wsa:EndpointReference' of XML schema type 'wsa:EndpointReference' */
        struct wsa__EndpointReferenceType wsa__EndpointReference;
        /** Optional element 'wsdd:Types' of XML schema type 'xsd:QName' */
        char *Types;
        /** Optional element 'wsdd:Scopes' of XML schema type 'wsdd:ScopesType' */
        struct wsdd__ScopesType *Scopes;
        /** Optional element 'wsdd:XAddrs' of XML schema type 'wsdd:UriListType' */
        char *XAddrs;
        /** Required element 'wsdd:MetadataVersion' of XML schema type 'xsd:unsignedInt' */
        unsigned int MetadataVersion;
};
#endif

/* wsdd10.h:73 */
#ifndef SOAP_TYPE_wsdd__SecurityType
#define SOAP_TYPE_wsdd__SecurityType (52)
/* complex XML schema type 'wsdd:SecurityType': */
struct wsdd__SecurityType {
        /** Optional element 'wsdd:Sig' of XML schema type 'wsdd:SigType' */
        struct wsdd__SigType *Sig;
};
#endif

/* wsdd10.h:75 */
#ifndef SOAP_TYPE_wsdd__SigType
#define SOAP_TYPE_wsdd__SigType (53)
/* complex XML schema type 'wsdd:SigType': */
struct wsdd__SigType {
        /** Required attribute 'Scheme' of XML schema type 'xsd:string' */
        char *Scheme;
        /** Optional attribute 'KeyId' of XML schema type 'xsd:string' */
        char *KeyId;
        /** Required attribute 'Refs' of XML schema type 'xsd:string' */
        char *Refs;
        /** Required attribute 'Sig' of XML schema type 'xsd:string' */
        char *Sig;
};
#endif

/* wsdd10.h:71 */
#ifndef SOAP_TYPE_wsdd__ScopesType
#define SOAP_TYPE_wsdd__ScopesType (51)
/* simple XML schema type 'wsdd:ScopesType': */
struct wsdd__ScopesType {
        /** Simple content of XML schema type 'wsdd:UriListType' wrapped by this struct */
        char *__item;
        /** Optional attribute 'MatchBy' of XML schema type 'xsd:string' */
        char *MatchBy;
};
#endif

/* wsdd10.h:77 */
#ifndef SOAP_TYPE_wsdd__AppSequenceType
#define SOAP_TYPE_wsdd__AppSequenceType (54)
/* complex XML schema type 'wsdd:AppSequenceType': */
struct wsdd__AppSequenceType {
        /** Required attribute 'InstanceId' of XML schema type 'xsd:unsignedInt' */
        unsigned int InstanceId;
        /** Optional attribute 'SequenceId' of XML schema type 'xsd:string' */
        char *SequenceId;
        /** Required attribute 'MessageNumber' of XML schema type 'xsd:unsignedInt' */
        unsigned int MessageNumber;
};
#endif

/* wsdx.h:67 */
#ifndef SOAP_TYPE___wsdd__Hello
#define SOAP_TYPE___wsdd__Hello (82)
/* Wrapper: */
struct __wsdd__Hello {
        /** Optional element 'wsdd:Hello' of XML schema type 'wsdd:HelloType' */
        struct wsdd__HelloType *wsdd__Hello;
};
#endif

/* wsdx.h:76 */
#ifndef SOAP_TYPE___wsdd__Bye
#define SOAP_TYPE___wsdd__Bye (85)
/* Wrapper: */
struct __wsdd__Bye {
        /** Optional element 'wsdd:Bye' of XML schema type 'wsdd:ByeType' */
        struct wsdd__ByeType *wsdd__Bye;
};
#endif

/* wsdx.h:85 */
#ifndef SOAP_TYPE___wsdd__Probe
#define SOAP_TYPE___wsdd__Probe (88)
/* Wrapper: */
struct __wsdd__Probe {
        /** Optional element 'wsdd:Probe' of XML schema type 'wsdd:ProbeType' */
        struct wsdd__ProbeType *wsdd__Probe;
};
#endif

/* wsdx.h:94 */
#ifndef SOAP_TYPE___wsdd__ProbeMatches
#define SOAP_TYPE___wsdd__ProbeMatches (91)
/* Wrapper: */
struct __wsdd__ProbeMatches {
        /** Optional element 'wsdd:ProbeMatches' of XML schema type 'wsdd:ProbeMatchesType' */
        struct wsdd__ProbeMatchesType *wsdd__ProbeMatches;
};
#endif

/* wsdx.h:103 */
#ifndef SOAP_TYPE___wsdd__Resolve
#define SOAP_TYPE___wsdd__Resolve (94)
/* Wrapper: */
struct __wsdd__Resolve {
        /** Optional element 'wsdd:Resolve' of XML schema type 'wsdd:ResolveType' */
        struct wsdd__ResolveType *wsdd__Resolve;
};
#endif

/* wsdx.h:112 */
#ifndef SOAP_TYPE___wsdd__ResolveMatches
#define SOAP_TYPE___wsdd__ResolveMatches (97)
/* Wrapper: */
struct __wsdd__ResolveMatches {
        /** Optional element 'wsdd:ResolveMatches' of XML schema type 'wsdd:ResolveMatchesType' */
        struct wsdd__ResolveMatchesType *wsdd__ResolveMatches;
};
#endif

/* onvif.h:298 */
#ifndef SOAP_TYPE___tdn__Hello
#define SOAP_TYPE___tdn__Hello (99)
/* Wrapper: */
struct __tdn__Hello {
        /** Required element 'tdn:Hello' of XML schema type 'wsdd:HelloType' */
        struct wsdd__HelloType tdn__Hello;
};
#endif

/* onvif.h:353 */
#ifndef SOAP_TYPE___tdn__Bye
#define SOAP_TYPE___tdn__Bye (101)
/* Wrapper: */
struct __tdn__Bye {
        /** Required element 'tdn:Bye' of XML schema type 'wsdd:ByeType' */
        struct wsdd__ByeType tdn__Bye;
};
#endif

/* onvif.h:408 */
#ifndef SOAP_TYPE___tdn__Probe
#define SOAP_TYPE___tdn__Probe (103)
/* Wrapper: */
struct __tdn__Probe {
        /** Required element 'tdn:Probe' of XML schema type 'wsdd:ProbeType' */
        struct wsdd__ProbeType tdn__Probe;
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/* wsa.h:224 */
#ifndef SOAP_TYPE__wsa__EndpointReference
#define SOAP_TYPE__wsa__EndpointReference (19)
typedef struct wsa__EndpointReferenceType _wsa__EndpointReference;
#endif

/* wsa.h:227 */
#ifndef SOAP_TYPE__wsa__MessageID
#define SOAP_TYPE__wsa__MessageID (20)
typedef char *_wsa__MessageID;
#endif

/* wsa.h:230 */
#ifndef SOAP_TYPE__wsa__RelatesTo
#define SOAP_TYPE__wsa__RelatesTo (21)
typedef struct wsa__Relationship _wsa__RelatesTo;
#endif

/* wsa.h:233 */
#ifndef SOAP_TYPE__wsa__To
#define SOAP_TYPE__wsa__To (22)
typedef char *_wsa__To;
#endif

/* wsa.h:236 */
#ifndef SOAP_TYPE__wsa__Action
#define SOAP_TYPE__wsa__Action (23)
typedef char *_wsa__Action;
#endif

/* wsa.h:239 */
#ifndef SOAP_TYPE__wsa__From
#define SOAP_TYPE__wsa__From (24)
typedef struct wsa__EndpointReferenceType _wsa__From;
#endif

/* wsa.h:242 */
#ifndef SOAP_TYPE__wsa__ReplyTo
#define SOAP_TYPE__wsa__ReplyTo (25)
typedef struct wsa__EndpointReferenceType _wsa__ReplyTo;
#endif

/* wsa.h:245 */
#ifndef SOAP_TYPE__wsa__FaultTo
#define SOAP_TYPE__wsa__FaultTo (26)
typedef struct wsa__EndpointReferenceType _wsa__FaultTo;
#endif

/* wsa.h:248 */
#ifndef SOAP_TYPE__wsa__ReplyAfter
#define SOAP_TYPE__wsa__ReplyAfter (28)
typedef unsigned int _wsa__ReplyAfter;
#endif

/* wsdd10.h:88 */
#ifndef SOAP_TYPE_wsdd__QNameListType
#define SOAP_TYPE_wsdd__QNameListType (55)
typedef _QName wsdd__QNameListType;
#endif

/* wsdd10.h:92 */
#ifndef SOAP_TYPE_wsdd__UriListType
#define SOAP_TYPE_wsdd__UriListType (56)
typedef char *wsdd__UriListType;
#endif

/* wsdd10.h:95 */
#ifndef SOAP_TYPE_wsdd__FaultCodeOpenType
#define SOAP_TYPE_wsdd__FaultCodeOpenType (57)
typedef char *wsdd__FaultCodeOpenType;
#endif

/* wsdd10.h:465 */
#ifndef SOAP_TYPE__wsdd__Hello
#define SOAP_TYPE__wsdd__Hello (64)
typedef struct wsdd__HelloType _wsdd__Hello;
#endif

/* wsdd10.h:468 */
#ifndef SOAP_TYPE__wsdd__Bye
#define SOAP_TYPE__wsdd__Bye (65)
typedef struct wsdd__ByeType _wsdd__Bye;
#endif

/* wsdd10.h:471 */
#ifndef SOAP_TYPE__wsdd__Probe
#define SOAP_TYPE__wsdd__Probe (66)
typedef struct wsdd__ProbeType _wsdd__Probe;
#endif

/* wsdd10.h:474 */
#ifndef SOAP_TYPE__wsdd__ProbeMatches
#define SOAP_TYPE__wsdd__ProbeMatches (67)
typedef struct wsdd__ProbeMatchesType _wsdd__ProbeMatches;
#endif

/* wsdd10.h:477 */
#ifndef SOAP_TYPE__wsdd__Resolve
#define SOAP_TYPE__wsdd__Resolve (68)
typedef struct wsdd__ResolveType _wsdd__Resolve;
#endif

/* wsdd10.h:480 */
#ifndef SOAP_TYPE__wsdd__ResolveMatches
#define SOAP_TYPE__wsdd__ResolveMatches (69)
typedef struct wsdd__ResolveMatchesType _wsdd__ResolveMatches;
#endif

/* wsdd10.h:483 */
#ifndef SOAP_TYPE__wsdd__Types
#define SOAP_TYPE__wsdd__Types (70)
typedef wsdd__QNameListType _wsdd__Types;
#endif

/* wsdd10.h:486 */
#ifndef SOAP_TYPE__wsdd__Scopes
#define SOAP_TYPE__wsdd__Scopes (71)
typedef struct wsdd__ScopesType _wsdd__Scopes;
#endif

/* wsdd10.h:489 */
#ifndef SOAP_TYPE__wsdd__XAddrs
#define SOAP_TYPE__wsdd__XAddrs (72)
typedef wsdd__UriListType _wsdd__XAddrs;
#endif

/* wsdd10.h:492 */
#ifndef SOAP_TYPE__wsdd__MetadataVersion
#define SOAP_TYPE__wsdd__MetadataVersion (73)
typedef unsigned int _wsdd__MetadataVersion;
#endif

/* wsdd10.h:495 */
#ifndef SOAP_TYPE__wsdd__SupportedMatchingRules
#define SOAP_TYPE__wsdd__SupportedMatchingRules (74)
typedef wsdd__UriListType _wsdd__SupportedMatchingRules;
#endif

/* wsdd10.h:498 */
#ifndef SOAP_TYPE__wsdd__Security
#define SOAP_TYPE__wsdd__Security (75)
typedef struct wsdd__SecurityType _wsdd__Security;
#endif

/* wsdd10.h:501 */
#ifndef SOAP_TYPE__wsdd__Sig
#define SOAP_TYPE__wsdd__Sig (76)
typedef struct wsdd__SigType _wsdd__Sig;
#endif

/* wsdd10.h:504 */
#ifndef SOAP_TYPE__wsdd__AppSequence
#define SOAP_TYPE__wsdd__AppSequence (77)
typedef struct wsdd__AppSequenceType _wsdd__AppSequence;
#endif

/* wsdd10.h:515 */
#ifndef SOAP_TYPE__wsdd__Id
#define SOAP_TYPE__wsdd__Id (78)
typedef char *_wsdd__Id;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* _wsdd__MetadataVersion has binding name '_wsdd__MetadataVersion' for type '' */
#ifndef SOAP_TYPE__wsdd__MetadataVersion
#define SOAP_TYPE__wsdd__MetadataVersion (73)
#endif

/* _wsa__ReplyAfter has binding name '_wsa__ReplyAfter' for type '' */
#ifndef SOAP_TYPE__wsa__ReplyAfter
#define SOAP_TYPE__wsa__ReplyAfter (28)
#endif

/* unsigned int has binding name 'unsignedInt' for type 'xsd:unsignedInt' */
#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (27)
#endif

/* enum wsdd__FaultCodeType has binding name 'wsdd__FaultCodeType' for type 'wsdd:FaultCodeType' */
#ifndef SOAP_TYPE_wsdd__FaultCodeType
#define SOAP_TYPE_wsdd__FaultCodeType (58)
#endif

/* enum wsa__FaultSubcodeValues has binding name 'wsa__FaultSubcodeValues' for type 'wsa:FaultSubcodeValues' */
#ifndef SOAP_TYPE_wsa__FaultSubcodeValues
#define SOAP_TYPE_wsa__FaultSubcodeValues (13)
#endif

/* enum wsa__RelationshipTypeValues has binding name 'wsa__RelationshipTypeValues' for type 'wsa:RelationshipTypeValues' */
#ifndef SOAP_TYPE_wsa__RelationshipTypeValues
#define SOAP_TYPE_wsa__RelationshipTypeValues (12)
#endif

/* _wsdd__AppSequence has binding name '_wsdd__AppSequence' for type '' */
#ifndef SOAP_TYPE__wsdd__AppSequence
#define SOAP_TYPE__wsdd__AppSequence (77)
#endif

/* _wsdd__Sig has binding name '_wsdd__Sig' for type '' */
#ifndef SOAP_TYPE__wsdd__Sig
#define SOAP_TYPE__wsdd__Sig (76)
#endif

/* _wsdd__Security has binding name '_wsdd__Security' for type '' */
#ifndef SOAP_TYPE__wsdd__Security
#define SOAP_TYPE__wsdd__Security (75)
#endif

/* _wsdd__Scopes has binding name '_wsdd__Scopes' for type '' */
#ifndef SOAP_TYPE__wsdd__Scopes
#define SOAP_TYPE__wsdd__Scopes (71)
#endif

/* _wsdd__ResolveMatches has binding name '_wsdd__ResolveMatches' for type '' */
#ifndef SOAP_TYPE__wsdd__ResolveMatches
#define SOAP_TYPE__wsdd__ResolveMatches (69)
#endif

/* _wsdd__Resolve has binding name '_wsdd__Resolve' for type '' */
#ifndef SOAP_TYPE__wsdd__Resolve
#define SOAP_TYPE__wsdd__Resolve (68)
#endif

/* _wsdd__ProbeMatches has binding name '_wsdd__ProbeMatches' for type '' */
#ifndef SOAP_TYPE__wsdd__ProbeMatches
#define SOAP_TYPE__wsdd__ProbeMatches (67)
#endif

/* _wsdd__Probe has binding name '_wsdd__Probe' for type '' */
#ifndef SOAP_TYPE__wsdd__Probe
#define SOAP_TYPE__wsdd__Probe (66)
#endif

/* _wsdd__Bye has binding name '_wsdd__Bye' for type '' */
#ifndef SOAP_TYPE__wsdd__Bye
#define SOAP_TYPE__wsdd__Bye (65)
#endif

/* _wsdd__Hello has binding name '_wsdd__Hello' for type '' */
#ifndef SOAP_TYPE__wsdd__Hello
#define SOAP_TYPE__wsdd__Hello (64)
#endif

/* struct wsdd__AppSequenceType has binding name 'wsdd__AppSequenceType' for type 'wsdd:AppSequenceType' */
#ifndef SOAP_TYPE_wsdd__AppSequenceType
#define SOAP_TYPE_wsdd__AppSequenceType (54)
#endif

/* struct wsdd__SigType has binding name 'wsdd__SigType' for type 'wsdd:SigType' */
#ifndef SOAP_TYPE_wsdd__SigType
#define SOAP_TYPE_wsdd__SigType (53)
#endif

/* struct wsdd__SecurityType has binding name 'wsdd__SecurityType' for type 'wsdd:SecurityType' */
#ifndef SOAP_TYPE_wsdd__SecurityType
#define SOAP_TYPE_wsdd__SecurityType (52)
#endif

/* struct wsdd__ScopesType has binding name 'wsdd__ScopesType' for type 'wsdd:ScopesType' */
#ifndef SOAP_TYPE_wsdd__ScopesType
#define SOAP_TYPE_wsdd__ScopesType (51)
#endif

/* struct wsdd__ResolveMatchType has binding name 'wsdd__ResolveMatchType' for type 'wsdd:ResolveMatchType' */
#ifndef SOAP_TYPE_wsdd__ResolveMatchType
#define SOAP_TYPE_wsdd__ResolveMatchType (50)
#endif

/* struct wsdd__ResolveMatchesType has binding name 'wsdd__ResolveMatchesType' for type 'wsdd:ResolveMatchesType' */
#ifndef SOAP_TYPE_wsdd__ResolveMatchesType
#define SOAP_TYPE_wsdd__ResolveMatchesType (49)
#endif

/* struct wsdd__ResolveType has binding name 'wsdd__ResolveType' for type 'wsdd:ResolveType' */
#ifndef SOAP_TYPE_wsdd__ResolveType
#define SOAP_TYPE_wsdd__ResolveType (48)
#endif

/* struct wsdd__ProbeMatchType has binding name 'wsdd__ProbeMatchType' for type 'wsdd:ProbeMatchType' */
#ifndef SOAP_TYPE_wsdd__ProbeMatchType
#define SOAP_TYPE_wsdd__ProbeMatchType (47)
#endif

/* struct wsdd__ProbeMatchesType has binding name 'wsdd__ProbeMatchesType' for type 'wsdd:ProbeMatchesType' */
#ifndef SOAP_TYPE_wsdd__ProbeMatchesType
#define SOAP_TYPE_wsdd__ProbeMatchesType (46)
#endif

/* struct wsdd__ProbeType has binding name 'wsdd__ProbeType' for type 'wsdd:ProbeType' */
#ifndef SOAP_TYPE_wsdd__ProbeType
#define SOAP_TYPE_wsdd__ProbeType (45)
#endif

/* struct wsdd__ByeType has binding name 'wsdd__ByeType' for type 'wsdd:ByeType' */
#ifndef SOAP_TYPE_wsdd__ByeType
#define SOAP_TYPE_wsdd__ByeType (44)
#endif

/* struct wsdd__HelloType has binding name 'wsdd__HelloType' for type 'wsdd:HelloType' */
#ifndef SOAP_TYPE_wsdd__HelloType
#define SOAP_TYPE_wsdd__HelloType (43)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (42)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (38)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (36)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (34)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (29)
#endif

/* _wsa__FaultTo has binding name '_wsa__FaultTo' for type '' */
#ifndef SOAP_TYPE__wsa__FaultTo
#define SOAP_TYPE__wsa__FaultTo (26)
#endif

/* _wsa__ReplyTo has binding name '_wsa__ReplyTo' for type '' */
#ifndef SOAP_TYPE__wsa__ReplyTo
#define SOAP_TYPE__wsa__ReplyTo (25)
#endif

/* _wsa__From has binding name '_wsa__From' for type '' */
#ifndef SOAP_TYPE__wsa__From
#define SOAP_TYPE__wsa__From (24)
#endif

/* _wsa__RelatesTo has binding name '_wsa__RelatesTo' for type '' */
#ifndef SOAP_TYPE__wsa__RelatesTo
#define SOAP_TYPE__wsa__RelatesTo (21)
#endif

/* _wsa__EndpointReference has binding name '_wsa__EndpointReference' for type '' */
#ifndef SOAP_TYPE__wsa__EndpointReference
#define SOAP_TYPE__wsa__EndpointReference (19)
#endif

/* struct wsa__Relationship has binding name 'wsa__Relationship' for type 'wsa:Relationship' */
#ifndef SOAP_TYPE_wsa__Relationship
#define SOAP_TYPE_wsa__Relationship (11)
#endif

/* struct wsa__ServiceNameType has binding name 'wsa__ServiceNameType' for type 'wsa:ServiceNameType' */
#ifndef SOAP_TYPE_wsa__ServiceNameType
#define SOAP_TYPE_wsa__ServiceNameType (10)
#endif

/* struct wsa__ReferenceParametersType has binding name 'wsa__ReferenceParametersType' for type 'wsa:ReferenceParametersType' */
#ifndef SOAP_TYPE_wsa__ReferenceParametersType
#define SOAP_TYPE_wsa__ReferenceParametersType (9)
#endif

/* struct wsa__ReferencePropertiesType has binding name 'wsa__ReferencePropertiesType' for type 'wsa:ReferencePropertiesType' */
#ifndef SOAP_TYPE_wsa__ReferencePropertiesType
#define SOAP_TYPE_wsa__ReferencePropertiesType (8)
#endif

/* struct wsa__EndpointReferenceType has binding name 'wsa__EndpointReferenceType' for type 'wsa:EndpointReferenceType' */
#ifndef SOAP_TYPE_wsa__EndpointReferenceType
#define SOAP_TYPE_wsa__EndpointReferenceType (7)
#endif

/* struct wsdd__ResolveMatchesType * has binding name 'PointerTowsdd__ResolveMatchesType' for type 'wsdd:ResolveMatchesType' */
#ifndef SOAP_TYPE_PointerTowsdd__ResolveMatchesType
#define SOAP_TYPE_PointerTowsdd__ResolveMatchesType (95)
#endif

/* struct wsdd__ResolveType * has binding name 'PointerTowsdd__ResolveType' for type 'wsdd:ResolveType' */
#ifndef SOAP_TYPE_PointerTowsdd__ResolveType
#define SOAP_TYPE_PointerTowsdd__ResolveType (92)
#endif

/* struct wsdd__ProbeMatchesType * has binding name 'PointerTowsdd__ProbeMatchesType' for type 'wsdd:ProbeMatchesType' */
#ifndef SOAP_TYPE_PointerTowsdd__ProbeMatchesType
#define SOAP_TYPE_PointerTowsdd__ProbeMatchesType (89)
#endif

/* struct wsdd__ProbeType * has binding name 'PointerTowsdd__ProbeType' for type 'wsdd:ProbeType' */
#ifndef SOAP_TYPE_PointerTowsdd__ProbeType
#define SOAP_TYPE_PointerTowsdd__ProbeType (86)
#endif

/* struct wsdd__ByeType * has binding name 'PointerTowsdd__ByeType' for type 'wsdd:ByeType' */
#ifndef SOAP_TYPE_PointerTowsdd__ByeType
#define SOAP_TYPE_PointerTowsdd__ByeType (83)
#endif

/* struct wsdd__HelloType * has binding name 'PointerTowsdd__HelloType' for type 'wsdd:HelloType' */
#ifndef SOAP_TYPE_PointerTowsdd__HelloType
#define SOAP_TYPE_PointerTowsdd__HelloType (80)
#endif

/* struct wsdd__AppSequenceType * has binding name 'PointerTowsdd__AppSequenceType' for type 'wsdd:AppSequenceType' */
#ifndef SOAP_TYPE_PointerTowsdd__AppSequenceType
#define SOAP_TYPE_PointerTowsdd__AppSequenceType (79)
#endif

/* _wsdd__Id has binding name '_wsdd__Id' for type '' */
#ifndef SOAP_TYPE__wsdd__Id
#define SOAP_TYPE__wsdd__Id (78)
#endif

/* _wsdd__SupportedMatchingRules has binding name '_wsdd__SupportedMatchingRules' for type '' */
#ifndef SOAP_TYPE__wsdd__SupportedMatchingRules
#define SOAP_TYPE__wsdd__SupportedMatchingRules (74)
#endif

/* _wsdd__XAddrs has binding name '_wsdd__XAddrs' for type '' */
#ifndef SOAP_TYPE__wsdd__XAddrs
#define SOAP_TYPE__wsdd__XAddrs (72)
#endif

/* _wsdd__Types has binding name '_wsdd__Types' for type 'xsd:QName' */
#ifndef SOAP_TYPE__wsdd__Types
#define SOAP_TYPE__wsdd__Types (70)
#endif

/* struct wsdd__SigType * has binding name 'PointerTowsdd__SigType' for type 'wsdd:SigType' */
#ifndef SOAP_TYPE_PointerTowsdd__SigType
#define SOAP_TYPE_PointerTowsdd__SigType (63)
#endif

/* struct wsdd__ResolveMatchType * has binding name 'PointerTowsdd__ResolveMatchType' for type 'wsdd:ResolveMatchType' */
#ifndef SOAP_TYPE_PointerTowsdd__ResolveMatchType
#define SOAP_TYPE_PointerTowsdd__ResolveMatchType (62)
#endif

/* struct wsdd__ProbeMatchType * has binding name 'PointerTowsdd__ProbeMatchType' for type 'wsdd:ProbeMatchType' */
#ifndef SOAP_TYPE_PointerTowsdd__ProbeMatchType
#define SOAP_TYPE_PointerTowsdd__ProbeMatchType (61)
#endif

/* unsigned int * has binding name 'PointerTounsignedInt' for type 'xsd:unsignedInt' */
#ifndef SOAP_TYPE_PointerTounsignedInt
#define SOAP_TYPE_PointerTounsignedInt (60)
#endif

/* struct wsdd__ScopesType * has binding name 'PointerTowsdd__ScopesType' for type 'wsdd:ScopesType' */
#ifndef SOAP_TYPE_PointerTowsdd__ScopesType
#define SOAP_TYPE_PointerTowsdd__ScopesType (59)
#endif

/* wsdd__FaultCodeOpenType has binding name 'wsdd__FaultCodeOpenType' for type 'wsdd:FaultCodeOpenType' */
#ifndef SOAP_TYPE_wsdd__FaultCodeOpenType
#define SOAP_TYPE_wsdd__FaultCodeOpenType (57)
#endif

/* wsdd__UriListType has binding name 'wsdd__UriListType' for type 'wsdd:UriListType' */
#ifndef SOAP_TYPE_wsdd__UriListType
#define SOAP_TYPE_wsdd__UriListType (56)
#endif

/* wsdd__QNameListType has binding name 'wsdd__QNameListType' for type 'xsd:QName' */
#ifndef SOAP_TYPE_wsdd__QNameListType
#define SOAP_TYPE_wsdd__QNameListType (55)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (39)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (37)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (35)
#endif

/* struct wsa__EndpointReferenceType * has binding name 'PointerTo_wsa__FaultTo' for type '' */
#ifndef SOAP_TYPE_PointerTo_wsa__FaultTo
#define SOAP_TYPE_PointerTo_wsa__FaultTo (33)
#endif

/* struct wsa__EndpointReferenceType * has binding name 'PointerTo_wsa__ReplyTo' for type '' */
#ifndef SOAP_TYPE_PointerTo_wsa__ReplyTo
#define SOAP_TYPE_PointerTo_wsa__ReplyTo (32)
#endif

/* struct wsa__EndpointReferenceType * has binding name 'PointerTo_wsa__From' for type '' */
#ifndef SOAP_TYPE_PointerTo_wsa__From
#define SOAP_TYPE_PointerTo_wsa__From (31)
#endif

/* struct wsa__Relationship * has binding name 'PointerTo_wsa__RelatesTo' for type '' */
#ifndef SOAP_TYPE_PointerTo_wsa__RelatesTo
#define SOAP_TYPE_PointerTo_wsa__RelatesTo (30)
#endif

/* _wsa__Action has binding name '_wsa__Action' for type '' */
#ifndef SOAP_TYPE__wsa__Action
#define SOAP_TYPE__wsa__Action (23)
#endif

/* _wsa__To has binding name '_wsa__To' for type '' */
#ifndef SOAP_TYPE__wsa__To
#define SOAP_TYPE__wsa__To (22)
#endif

/* _wsa__MessageID has binding name '_wsa__MessageID' for type '' */
#ifndef SOAP_TYPE__wsa__MessageID
#define SOAP_TYPE__wsa__MessageID (20)
#endif

/* char ** has binding name 'PointerTo_XML' for type '' */
#ifndef SOAP_TYPE_PointerTo_XML
#define SOAP_TYPE_PointerTo_XML (18)
#endif

/* struct wsa__ServiceNameType * has binding name 'PointerTowsa__ServiceNameType' for type 'wsa:ServiceNameType' */
#ifndef SOAP_TYPE_PointerTowsa__ServiceNameType
#define SOAP_TYPE_PointerTowsa__ServiceNameType (17)
#endif

/* char ** has binding name 'PointerTo_QName' for type '' */
#ifndef SOAP_TYPE_PointerTo_QName
#define SOAP_TYPE_PointerTo_QName (16)
#endif

/* struct wsa__ReferenceParametersType * has binding name 'PointerTowsa__ReferenceParametersType' for type 'wsa:ReferenceParametersType' */
#ifndef SOAP_TYPE_PointerTowsa__ReferenceParametersType
#define SOAP_TYPE_PointerTowsa__ReferenceParametersType (15)
#endif

/* struct wsa__ReferencePropertiesType * has binding name 'PointerTowsa__ReferencePropertiesType' for type 'wsa:ReferencePropertiesType' */
#ifndef SOAP_TYPE_PointerTowsa__ReferencePropertiesType
#define SOAP_TYPE_PointerTowsa__ReferencePropertiesType (14)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    /** Web service one-way asynchronous operation 'soap_send_SOAP_ENV__Fault' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send_SOAP_ENV__Fault(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail);
    /** Web service one-way asynchronous operation 'soap_recv_SOAP_ENV__Fault' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *_param_1);
    /** Web service one-way asynchronous operation 'soap_send___wsdd__Hello' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___wsdd__Hello(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__HelloType *wsdd__Hello);
    /** Web service one-way asynchronous operation 'soap_recv___wsdd__Hello' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___wsdd__Hello(struct soap *soap, struct __wsdd__Hello *_param_1);
    /** Web service one-way asynchronous operation 'soap_send___wsdd__Bye' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___wsdd__Bye(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__ByeType *wsdd__Bye);
    /** Web service one-way asynchronous operation 'soap_recv___wsdd__Bye' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___wsdd__Bye(struct soap *soap, struct __wsdd__Bye *_param_1);
    /** Web service one-way asynchronous operation 'soap_send___wsdd__Probe' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___wsdd__Probe(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__ProbeType *wsdd__Probe);
    /** Web service one-way asynchronous operation 'soap_recv___wsdd__Probe' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___wsdd__Probe(struct soap *soap, struct __wsdd__Probe *_param_1);
    /** Web service one-way asynchronous operation 'soap_send___wsdd__ProbeMatches' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___wsdd__ProbeMatches(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__ProbeMatchesType *wsdd__ProbeMatches);
    /** Web service one-way asynchronous operation 'soap_recv___wsdd__ProbeMatches' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___wsdd__ProbeMatches(struct soap *soap, struct __wsdd__ProbeMatches *_param_1);
    /** Web service one-way asynchronous operation 'soap_send___wsdd__Resolve' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___wsdd__Resolve(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__ResolveType *wsdd__Resolve);
    /** Web service one-way asynchronous operation 'soap_recv___wsdd__Resolve' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___wsdd__Resolve(struct soap *soap, struct __wsdd__Resolve *_param_1);
    /** Web service one-way asynchronous operation 'soap_send___wsdd__ResolveMatches' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___wsdd__ResolveMatches(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__ResolveMatchesType *wsdd__ResolveMatches);
    /** Web service one-way asynchronous operation 'soap_recv___wsdd__ResolveMatches' */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___wsdd__ResolveMatches(struct soap *soap, struct __wsdd__ResolveMatches *_param_1);
    
    /** Web service synchronous operation 'soap_call___tdn__Hello' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___tdn__Hello(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__HelloType tdn__Hello, struct wsdd__ResolveType *tdn__HelloResponse);
    /** Web service asynchronous operation 'soap_send___tdn__Hello' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___tdn__Hello(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__HelloType tdn__Hello);
    /** Web service asynchronous operation 'soap_recv___tdn__Hello' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___tdn__Hello(struct soap *soap, struct wsdd__ResolveType *tdn__HelloResponse);
    
    /** Web service synchronous operation 'soap_call___tdn__Bye' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___tdn__Bye(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__ByeType tdn__Bye, struct wsdd__ResolveType *tdn__ByeResponse);
    /** Web service asynchronous operation 'soap_send___tdn__Bye' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___tdn__Bye(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__ByeType tdn__Bye);
    /** Web service asynchronous operation 'soap_recv___tdn__Bye' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___tdn__Bye(struct soap *soap, struct wsdd__ResolveType *tdn__ByeResponse);
    
    /** Web service synchronous operation 'soap_call___tdn__Probe' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_call___tdn__Probe(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__ProbeType tdn__Probe, struct wsdd__ProbeMatchesType *tdn__ProbeResponse);
    /** Web service asynchronous operation 'soap_send___tdn__Probe' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_send___tdn__Probe(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wsdd__ProbeType tdn__Probe);
    /** Web service asynchronous operation 'soap_recv___tdn__Probe' to receive a response message from the connected endpoint, returns SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 soap_recv___tdn__Probe(struct soap *soap, struct wsdd__ProbeMatchesType *tdn__ProbeResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/

    /** Web service one-way operation 'SOAP_ENV__Fault' implementation, should return value of soap_send_empty_response() to send HTTP Accept acknowledgment, or return an error code, or return SOAP_OK to immediately return without sending an HTTP response message */
    SOAP_FMAC5 int SOAP_FMAC6 SOAP_ENV__Fault(struct soap*, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail);
    /** Web service one-way operation '__wsdd__Hello' implementation, should return value of soap_send_empty_response() to send HTTP Accept acknowledgment, or return an error code, or return SOAP_OK to immediately return without sending an HTTP response message */
    SOAP_FMAC5 int SOAP_FMAC6 __wsdd__Hello(struct soap*, struct wsdd__HelloType *wsdd__Hello);
    /** Web service one-way operation '__wsdd__Bye' implementation, should return value of soap_send_empty_response() to send HTTP Accept acknowledgment, or return an error code, or return SOAP_OK to immediately return without sending an HTTP response message */
    SOAP_FMAC5 int SOAP_FMAC6 __wsdd__Bye(struct soap*, struct wsdd__ByeType *wsdd__Bye);
    /** Web service one-way operation '__wsdd__Probe' implementation, should return value of soap_send_empty_response() to send HTTP Accept acknowledgment, or return an error code, or return SOAP_OK to immediately return without sending an HTTP response message */
    SOAP_FMAC5 int SOAP_FMAC6 __wsdd__Probe(struct soap*, struct wsdd__ProbeType *wsdd__Probe);
    /** Web service one-way operation '__wsdd__ProbeMatches' implementation, should return value of soap_send_empty_response() to send HTTP Accept acknowledgment, or return an error code, or return SOAP_OK to immediately return without sending an HTTP response message */
    SOAP_FMAC5 int SOAP_FMAC6 __wsdd__ProbeMatches(struct soap*, struct wsdd__ProbeMatchesType *wsdd__ProbeMatches);
    /** Web service one-way operation '__wsdd__Resolve' implementation, should return value of soap_send_empty_response() to send HTTP Accept acknowledgment, or return an error code, or return SOAP_OK to immediately return without sending an HTTP response message */
    SOAP_FMAC5 int SOAP_FMAC6 __wsdd__Resolve(struct soap*, struct wsdd__ResolveType *wsdd__Resolve);
    /** Web service one-way operation '__wsdd__ResolveMatches' implementation, should return value of soap_send_empty_response() to send HTTP Accept acknowledgment, or return an error code, or return SOAP_OK to immediately return without sending an HTTP response message */
    SOAP_FMAC5 int SOAP_FMAC6 __wsdd__ResolveMatches(struct soap*, struct wsdd__ResolveMatchesType *wsdd__ResolveMatches);
    /** Web service operation '__tdn__Hello' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 __tdn__Hello(struct soap*, struct wsdd__HelloType tdn__Hello, struct wsdd__ResolveType *tdn__HelloResponse);
    /** Web service operation '__tdn__Bye' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 __tdn__Bye(struct soap*, struct wsdd__ByeType tdn__Bye, struct wsdd__ResolveType *tdn__ByeResponse);
    /** Web service operation '__tdn__Probe' implementation, should return SOAP_OK or error code */
    SOAP_FMAC5 int SOAP_FMAC6 __tdn__Probe(struct soap*, struct wsdd__ProbeType tdn__Probe, struct wsdd__ProbeMatchesType *tdn__ProbeResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_SOAP_ENV__Fault(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___wsdd__Hello(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___wsdd__Bye(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___wsdd__Probe(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___wsdd__ProbeMatches(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___wsdd__Resolve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___wsdd__ResolveMatches(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tdn__Hello(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tdn__Bye(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tdn__Probe(struct soap*);

#endif

/* End of soapStub.h */
